# Generated by Django 4.2.5 on 2023-09-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=200)),
                ("basic_talent", models.CharField(max_length=200)),
                ("company_name", models.CharField(max_length=300)),
                ("about_me", models.TextField()),
                ("company_url", models.CharField(max_length=2000)),
                ("resume_image", models.ImageField(upload_to="productimg")),
            ],
        ),
        migrations.CreateModel(
            name="Biodata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf", models.FileField(upload_to="resume/")),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("get_in_touch", models.TextField()),
                ("address", models.CharField(max_length=1000)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=50)),
            ],
        ),
    ]
