# Generated by Django 4.2.5 on 2023-09-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tesi_name", models.CharField(max_length=100)),
                ("testi_des", models.TextField()),
                ("testi_image", models.ImageField(upload_to="productimg")),
            ],
        ),
    ]
