# Generated by Django 4.2.5 on 2023-09-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0004_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Com_Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=300)),
                ("parcent", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=300)),
                ("parcent", models.CharField(max_length=30)),
            ],
        ),
    ]
