# Generated by Django 4.2.5 on 2023-09-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0006_clints_funfact_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorKTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_year", models.CharField(max_length=100)),
            ],
        ),
    ]
